// git init Usage: git init
// git add. Usage: git add [file] ...
// git config Usage: git config user.
// git commit. Usage: git commit -m “[ Type in the commit message]” ...
// git status Usage: git status
// git log. Usage: git log. ...
// git branch. Usage: git branch. ...
// git checkout. Usage: git checkout [branch name] ...
// Add remote Usage: git remote add origin git@github.com:User/UserRepo.git.
// git push. Usage: git push [variable name] master.
// git pull. Usage: git pull [variable name] master.

// for help visit this link http://guides.beanstalkapp.com/version-control/common-git-commands.html

// https://git-scm.com/download/win